import html2canvas from 'html2canvas';
import type { MarketState } from '../types';

function findBySym<T extends { sym: string }>(rows: T[] | undefined, sym: string): T | undefined {
  return rows?.find((row) => row.sym === sym);
}

export function buildShareTweetText(data: Pick<MarketState, 'etfs' | 'crypto' | 'metals' | 'global'>): string {
  const now = new Date();
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const spy = findBySym(data.etfs, 'SPY');
  const btc = findBySym(data.crypto, 'BTC');
  const gold = findBySym(data.metals, 'GC1!');
  const hsi = findBySym(data.global, '^HSI');

  const arrow = (v: number) => (v > 0 ? '▲' : '▼');
  const sign = (v: number) => (v > 0 ? '+' : '');

  return `📊 EOD Snapshot — ${months[now.getMonth()]} ${now.getDate()}, ${now.getFullYear()}

🇺🇸 SPY ${arrow(spy?.d1 ?? 0)} ${Math.abs(spy?.d1 ?? 0).toFixed(2)}%  WTD ${sign(spy?.w1 ?? 0)}${(spy?.w1 ?? 0).toFixed(2)}%
₿  BTC ${arrow(btc?.d1 ?? 0)} ${Math.abs(btc?.d1 ?? 0).toFixed(2)}%
🥇 Gold ${arrow(gold?.d1 ?? 0)} ${Math.abs(gold?.d1 ?? 0).toFixed(2)}%
🇭🇰 HSI ${arrow(hsi?.d1 ?? 0)} ${Math.abs(hsi?.d1 ?? 0).toFixed(2)}%

#stocks #markets #trading #macro`;
}

export function buildClipboardSnapshot(data: Pick<MarketState, 'etfs' | 'crypto' | 'metals' | 'dxvix'>): string {
  const now = new Date();
  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];
  const spy = findBySym(data.etfs, 'SPY');
  const qqq = findBySym(data.etfs, 'QQQ');
  const btc = findBySym(data.crypto, 'BTC');
  const gold = findBySym(data.metals, 'GC1!');
  const vix = findBySym(data.dxvix, 'CBOE:VIX');
  const sign = (v: number) => (v > 0 ? '+' : '');

  return `MARKET COMMAND CENTER — EOD SNAPSHOT
${months[now.getMonth()]} ${now.getDate()}, ${now.getFullYear()}
${'─'.repeat(52)}

US EQUITIES
  SPY:  ${sign(spy?.d1 ?? 0)}${(spy?.d1 ?? 0).toFixed(2)}% 1D | ${sign(spy?.w1 ?? 0)}${(spy?.w1 ?? 0).toFixed(2)}% WTD | ${sign(spy?.ytd ?? 0)}${(spy?.ytd ?? 0).toFixed(2)}% YTD
  QQQ:  ${sign(qqq?.d1 ?? 0)}${(qqq?.d1 ?? 0).toFixed(2)}% 1D | ${sign(qqq?.w1 ?? 0)}${(qqq?.w1 ?? 0).toFixed(2)}% WTD | ${sign(qqq?.ytd ?? 0)}${(qqq?.ytd ?? 0).toFixed(2)}% YTD

VOLATILITY
  VIX:  ${(vix?.price ?? 0).toFixed(2)} (${sign(vix?.d1 ?? 0)}${(vix?.d1 ?? 0).toFixed(2)}% 1D)

CRYPTO
  BTC:  $${(btc?.price ?? 0).toLocaleString()} | ${sign(btc?.d1 ?? 0)}${(btc?.d1 ?? 0).toFixed(2)}% 1D

COMMODITIES
  Gold: $${(gold?.price ?? 0).toFixed(0)} | ${sign(gold?.d1 ?? 0)}${(gold?.d1 ?? 0).toFixed(2)}% 1D

— Generated by MCC//PRO`;
}

async function captureElement(element: HTMLElement, scale: number): Promise<HTMLCanvasElement> {
  return html2canvas(element, {
    backgroundColor: '#ffffff',
    scale,
    useCORS: true,
    allowTaint: true,
    logging: false,
    ignoreElements: (el) => el.tagName === 'IFRAME',
    windowWidth: document.documentElement.scrollWidth,
    windowHeight: document.documentElement.scrollHeight,
  });
}

export async function downloadDashboardSnapshot(
  element: HTMLElement,
  onFlash?: () => void
): Promise<void> {
  onFlash?.();
  const canvas = await captureElement(element, 1.4);
  const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png'));
  if (!blob) throw new Error('Failed to create PNG');

  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = `MCC-${new Date().toISOString().slice(0, 10)}.png`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export async function shareDashboardToX(element: HTMLElement, tweetText?: string): Promise<'clipboard' | 'download'> {
  const canvas = await captureElement(element, window.devicePixelRatio || 1);
  const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png'));
  if (!blob) throw new Error('Failed to create PNG');

  const text =
    tweetText ??
    `Market Dashboard — ${new Date().toLocaleDateString('en-HK', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    })} #markets #trading`;

  const tweetUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`;

  if (navigator.clipboard?.write) {
    try {
      await navigator.clipboard.write([new ClipboardItem({ 'image/png': blob })]);
      window.open(tweetUrl, '_blank');
      return 'clipboard';
    } catch {
      window.open(tweetUrl, '_blank');
      return 'download';
    }
  }

  const url = canvas.toDataURL('image/png');
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = `market-snapshot-${new Date().toISOString().slice(0, 10)}.png`;
  anchor.click();
  window.open(tweetUrl, '_blank');
  return 'download';
}

export async function copySnapshotText(text: string): Promise<void> {
  await navigator.clipboard.writeText(text);
}
